---
name: Catalyst-Plugin-I18N-DBI
version: v0.2.4
author:
  - 'Matthias Dietrich <perl@rainboxx.de>'
abstract: DBI based I18N for Catalyst
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DBI: 0
  I18N::LangTags: 0
  I18N::LangTags::Detect: 0
  Locale::Maketext: 0
  Locale::Maketext::Lexicon::DBI: v0.2.0
  NEXT: 0
  Task::Weaken: 0
  Test::More: 0
  version: 0
configure_requires:
  Module::Build: 0.35
provides:
  Catalyst::Plugin::I18N::DBI:
    file: lib/Catalyst/Plugin/I18N/DBI.pm
    version: v0.2.4
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
